# Generated by Django 5.0.9 on 2026-08-04 14:35

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.UserManagerFromQuerySet()),
            ],
        ),
    ]
