# Generated by Django 5.0.9 on 2026-08-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('username', 'Username'), ('ip', 'IP address')], max_length=10)),
                ('key', models.CharField(help_text='The username or IP address this applies to.', max_length=255)),
                ('stage', models.PositiveIntegerField(default=0, help_text='Number of lockouts so far. Each one doubles the wait.')),
                ('locked_until', models.DateTimeField(blank=True, help_text='End of the current lockout, used to tell episodes apart.', null=True)),
                ('last_lockout_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'sign-in lockout',
                'ordering': ['-last_lockout_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='loginlockout',
            constraint=models.UniqueConstraint(fields=('kind', 'key'), name='uniq_login_lockout_kind_key'),
        ),
    ]
