# Generated by Django 5.0.9 on 2026-08-16 17:58

import django.core.validators
from django.db import migrations, models

from apps.accounts.models import OFFICE_COLOURS


def assign_colours(apps, schema_editor):
    """Give every existing office a colour.

    Office.save() does this for new rows, but a migration gets the historical
    model, which has no custom save() — so without this every office already in
    the database would stay blank and fall back to the same grey, and the
    feature would look broken on exactly the installations that have data.

    Ordered by sort_order then code so the assignment is deterministic and two
    people migrating the same data end up with the same colours.
    """
    Office = apps.get_model("accounts", "Office")
    for index, office in enumerate(Office.objects.order_by("sort_order", "code")):
        Office.objects.filter(pk=office.pk).update(
            colour=OFFICE_COLOURS[index % len(OFFICE_COLOURS)]
        )


def clear_colours(apps, schema_editor):
    apps.get_model("accounts", "Office").objects.update(colour="")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginlockout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='colour',
            field=models.CharField(blank=True, help_text='Identifies this office at a glance wherever it appears. Leave blank to be given an unused colour automatically.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a colour as six hex digits, for example #16697A.')], verbose_name='badge colour'),
        ),
        migrations.RunPython(assign_colours, clear_colours),
    ]
