# Generated by Django 5.2.17 on 2026-09-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_med_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_email',
            field=models.EmailField(blank=True, editable=False, max_length=254),
        ),
    ]
