# Generated by Django 5.0.9 on 2026-08-04 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Short code, e.g. MEMO.', max_length=24, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('retention_years', models.PositiveSmallIntegerField(default=5, help_text='How long records of this type are normally kept.')),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'document type',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MetadataFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text='Machine key, e.g. control_number. Never change it later.', max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('LONG_TEXT', 'Long text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('CHOICE', 'Choice list'), ('BOOLEAN', 'Yes / No')], default='TEXT', max_length=16)),
                ('choices_csv', models.CharField(blank=True, help_text='Comma-separated options (choice fields only).', max_length=500)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('is_searchable', models.BooleanField(default=True, help_text='Include the value in the search index.')),
                ('show_in_list', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'metadata field',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=72, unique=True)),
                ('category', models.CharField(choices=[('SUBJECT', 'Subject'), ('PROCESS', 'Process'), ('OFFICE', 'Office'), ('PROJECT', 'Project'), ('OTHER', 'Other')], default='SUBJECT', max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TagRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('pattern', models.CharField(help_text='Phrase, comma-separated words, or regular expression depending on match type.', max_length=255)),
                ('match_type', models.CharField(choices=[('CONTAINS', 'Text contains phrase'), ('ALL_WORDS', 'Text contains all words'), ('ANY_WORD', 'Text contains any word'), ('REGEX', 'Regular expression')], default='CONTAINS', max_length=16)),
                ('search_field', models.CharField(choices=[('FULL_TEXT', 'Full extracted text'), ('TITLE', 'Title / filename'), ('FIRST_PAGE', 'First 2000 characters')], default='FULL_TEXT', max_length=16)),
                ('suggest_metadata_key', models.CharField(blank=True, help_text='Optional metadata field key to fill.', max_length=64)),
                ('suggest_metadata_value', models.CharField(blank=True, max_length=255)),
                ('confidence', models.FloatField(default=0.8, help_text='0.0 – 1.0 confidence when this rule fires.')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Lower runs first.')),
                ('is_active', models.BooleanField(default=True)),
                ('suggest_document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.documenttype')),
                ('suggest_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_rules', to='accounts.office')),
                ('suggest_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.tag')),
            ],
            options={
                'verbose_name': 'metadata rule',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('LOGIN', 'Signed in'), ('LOGIN_FAILED', 'Failed sign-in'), ('LOGOUT', 'Signed out'), ('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('ROUTE', 'Routed'), ('RECEIVE', 'Confirmed receipt'), ('COMPLETE', 'Completed'), ('ARCHIVE', 'Archived'), ('DOWNLOAD', 'Downloaded'), ('SEARCH', 'Searched'), ('PERMISSION', 'Changed access')], max_length=16)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='core_auditl_target__6c66b3_idx'), models.Index(fields=['action', '-created_at'], name='core_auditl_action_d80c2d_idx')],
            },
        ),
    ]
