# Generated by Django 5.0.9 on 2026-08-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_cache_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Signed in'), ('LOGIN_FAILED', 'Failed sign-in'), ('LOGOUT', 'Signed out'), ('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('ROUTE', 'Routed'), ('RECEIVE', 'Confirmed receipt'), ('COMPLETE', 'Completed'), ('ARCHIVE', 'Archived'), ('DOWNLOAD', 'Downloaded'), ('PRINT', 'Printed'), ('SEARCH', 'Searched'), ('PERMISSION', 'Changed access')], max_length=16),
        ),
    ]
