# Generated by Django 5.2.17 on 2026-08-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_notificationpreference_notificationread'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
