# Generated by Django 5.2.17 on 2026-08-18 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_office_colour'),
        ('core', '0005_notification_resolved_at'),
        ('documents', '0004_backfill_retention_dates'),
        ('tracking', '0003_rename_in_transit_to_pending_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_digest_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_urgent_enabled',
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('ROUTED', 'Needs receipt'), ('RECEIVED', 'Receipt confirmed'), ('COMPLETED', 'Completed'), ('SHARED', 'Shared with your office')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['office', 'resolved_at', '-created_at'], name='notif_office_resolved_created'),
        ),
        migrations.AddIndex(
            model_name='notificationread',
            index=models.Index(fields=['user'], name='notif_read_user_idx'),
        ),
    ]
