"""Two new notification kinds: UNRECEIVED and OVERDUE.

Both are raised by time passing rather than by an action, so they are
computed on a daily schedule (apps.core.tasks.chase_unreceived_and_overdue)
rather than at a hook. Choices only — no rows change, and nothing is
back-filled: a notice about a document that went unreceived last March is
not information anybody can act on now.
"""

# Generated by Django 5.0.9 on 2026-08-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_notificationpreference_email_digest_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('ROUTED', 'Needs receipt'), ('RECEIVED', 'Receipt confirmed'), ('COMPLETED', 'Completed'), ('SHARED', 'Shared with your office'), ('UNRECEIVED', 'Still not received'), ('OVERDUE', 'Past its deadline')], max_length=32),
        ),
    ]
