# Generated by Django 5.0.9 on 2026-09-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification_kinds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=120)),
                ('recurring', models.BooleanField(default=False, help_text='Repeats every year on this day and month, e.g. Rizal Day, 30 December.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date', 'name'],
            },
        ),
    ]
