# Generated by Django 5.2.17 on 2026-10-02 14:31

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_securitythrottle'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('opens_at', models.TimeField(default=datetime.time(8, 0))),
                ('closes_at', models.TimeField(default=datetime.time(17, 0))),
                ('break_start', models.TimeField(default=datetime.time(12, 0))),
                ('break_end', models.TimeField(default=datetime.time(13, 0))),
                ('working_days', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='one_office_schedule'), models.CheckConstraint(condition=models.Q(('working_days__gte', 1), ('working_days__lte', 7)), name='schedule_valid_week'), models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at'))), name='schedule_positive_day'), models.CheckConstraint(condition=models.Q(('break_start__gte', models.F('opens_at')), ('break_end__lte', models.F('closes_at')), ('break_end__gte', models.F('break_start'))), name='schedule_break_inside_day'), models.CheckConstraint(condition=models.Q(('break_end', models.F('closes_at')), ('break_start', models.F('opens_at')), _negated=True), name='schedule_has_office_time')],
            },
        ),
    ]
