# Generated by Django 5.0.9 on 2026-08-04 04:48

import apps.documents.models
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Short abstract shown in search results.')),
                ('source', models.CharField(choices=[('DTS', 'Archived from tracking'), ('UPLOAD', 'Uploaded file'), ('SCAN', 'Scanned document')], default='UPLOAD', max_length=8)),
                ('reference_number', models.CharField(blank=True, db_index=True, help_text='Tracking or control number, including numbers from paper records.', max_length=64)),
                ('document_date', models.DateField(blank=True, help_text='Date printed on the document.', null=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('author_name', models.CharField(blank=True, max_length=150, verbose_name='from / author')),
                ('recipient_name', models.CharField(blank=True, max_length=150, verbose_name='to / recipient')),
                ('signatory', models.CharField(blank=True, max_length=150)),
                ('page_count', models.PositiveSmallIntegerField(default=0)),
                ('access_level', models.CharField(choices=[('OFFICE', 'Owning office only'), ('OVPA', 'All OVPA offices'), ('RESTRICTED', 'Named offices or users only')], default='OFFICE', max_length=12)),
                ('retention_until', models.DateField(blank=True, null=True)),
                ('ocr_text', models.TextField(blank=True)),
                ('ocr_status', models.CharField(choices=[('PENDING', 'Waiting for text extraction'), ('RUNNING', 'Extracting'), ('DONE', 'Text extracted'), ('EMPTY', 'No text found'), ('FAILED', 'Extraction failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=8)),
                ('ocr_engine', models.CharField(blank=True, max_length=32)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('index_title', models.TextField(blank=True, editable=False)),
                ('index_meta', models.TextField(blank=True, editable=False)),
                ('index_extra', models.TextField(blank=True, editable=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.documenttype')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounts.office', verbose_name='owning office')),
                ('tags', models.ManyToManyField(blank=True, related_name='documents', to='core.tag')),
                ('tracking_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_document', to='tracking.trackingrecord')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='documents.document')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_grants_given', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_grants', to='accounts.office')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document access grant',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=400, upload_to=apps.documents.models.document_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('page_count', models.PositiveSmallIntegerField(default=0)),
                ('extracted_chars', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.document')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=500)),
                ('value_normalised', models.CharField(blank=True, db_index=True, editable=False, max_length=500)),
                ('source', models.CharField(default='USER', help_text='USER for typed values, RULE/AI for suggestions accepted by the uploader.', max_length=16)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_values', to='documents.document')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.metadatafielddefinition')),
            ],
            options={
                'verbose_name': 'metadata value',
                'verbose_name_plural': 'metadata values',
                'ordering': ['field__sort_order', 'field__label'],
            },
        ),
        migrations.CreateModel(
            name='MetadataSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(default='rules', max_length=32)),
                ('engine_version', models.CharField(default='1.0', max_length=16)),
                ('suggested', models.JSONField(default=dict)),
                ('accepted', models.JSONField(blank=True, default=dict)),
                ('text_sample', models.TextField(blank=True, help_text='First part of the extracted text the engine saw.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='documents.document')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'metadata suggestion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('top_score', models.FloatField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('clicked_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_clicks', to='documents.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'search query log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='doc_search_vector_gin'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['office', 'year'], name='documents_d_office__8026cc_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', 'year'], name='documents_d_documen_0e3504_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='documents_d_created_71dced_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentaccessgrant',
            unique_together={('document', 'office', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='documentmetadata',
            unique_together={('document', 'field')},
        ),
    ]
