# Generated by Django 5.2.17 on 2026-08-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='allow_external_ocr',
            field=models.BooleanField(default=True, help_text='Allow scanned content to be sent to the configured external OCR provider.'),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_language',
            field=models.CharField(choices=[('auto', 'Automatic (English and Filipino)'), ('eng', 'English'), ('fil', 'Filipino')], default='auto', max_length=8),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_notes',
            field=models.TextField(blank=True, help_text='Operator-visible extraction and retry notes.'),
        ),
    ]
