# Generated by Django 5.2.17 on 2026-10-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_backfill_retention_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='allow_external_ocr',
            field=models.BooleanField(default=False, help_text='Allow scanned content to be sent to the configured external OCR provider.'),
        ),
    ]
