# Generated by Django 5.2.17 on 2026-10-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_allow_external_ocr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
