# Generated by Django 5.2.17 on 2026-10-06 07:34

from django.db import migrations, models


def backfill_types(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    alias = schema_editor.connection.alias
    through = Document.document_types.through
    batch = []
    for pk, type_id in Document.objects.using(alias).exclude(document_type_id=None).values_list("pk", "document_type_id").iterator(chunk_size=1000):
        batch.append(through(document_id=pk, documenttype_id=type_id))
        if len(batch) == 1000:
            through.objects.using(alias).bulk_create(batch, ignore_conflicts=True)
            batch = []
    if batch:
        through.objects.using(alias).bulk_create(batch, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_office_schedule'),
        ('documents', '0006_alter_document_page_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_types',
            field=models.ManyToManyField(blank=True, related_name='typed_documents', to='core.documenttype'),
        ),
        migrations.RunPython(backfill_types, migrations.RunPython.noop),
    ]
