# Generated by Django 5.0.9 on 2026-08-04 04:48

import apps.tracking.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(db_index=True, max_length=48, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('classification', models.CharField(choices=[('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential'), ('PUBLIC', 'Public')], default='INTERNAL', max_length=16)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], default='NORMAL', max_length=8)),
                ('instructions', models.TextField(help_text='Action required by the receiving office.')),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_TRANSIT', 'In transit'), ('RECEIVED', 'Received'), ('IN_PROCESS', 'In process'), ('FORWARDED', 'Forwarded'), ('RETURNED', 'Returned'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=16)),
                ('current_batch', models.PositiveSmallIntegerField(default=0)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('first_received_at', models.DateTimeField(blank=True, null=True)),
                ('last_movement_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_note', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_records', to=settings.AUTH_USER_MODEL)),
                ('current_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_records', to='accounts.office')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_records', to='core.documenttype')),
                ('originating_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originated_records', to='accounts.office')),
            ],
            options={
                'verbose_name': 'tracking record',
                'ordering': ['-last_movement_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('batch', models.PositiveSmallIntegerField(default=1, help_text='Steps sent together share a batch number.')),
                ('action', models.CharField(choices=[('SEND', 'Sent'), ('FORWARD', 'Forwarded'), ('RETURN', 'Returned')], default='SEND', max_length=8)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('instructions', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_note', models.TextField(blank=True)),
                ('from_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='steps_sent', to='accounts.office')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_steps_received', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_steps_sent', to=settings.AUTH_USER_MODEL)),
                ('to_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps_received', to='accounts.office')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_steps', to='tracking.trackingrecord')),
            ],
            options={
                'verbose_name': 'routing step',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='RecordActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Routed'), ('RECEIVED', 'Receipt confirmed'), ('REMARK', 'Remark added'), ('ATTACHMENT', 'File attached'), ('FORWARDED', 'Forwarded'), ('RETURNED', 'Returned'), ('COMPLETED', 'Marked completed'), ('ARCHIVED', 'Archived'), ('ACCESS', 'Access granted')], max_length=16)),
                ('batch', models.PositiveSmallIntegerField(default=0)),
                ('message', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_activities', to=settings.AUTH_USER_MODEL)),
                ('actor_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_activities', to='accounts.office')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tracking.trackingrecord')),
            ],
            options={
                'verbose_name': 'record activity',
                'verbose_name_plural': 'record activities',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecordAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_grants_given', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_grants', to='accounts.office')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_grants', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='tracking.trackingrecord')),
            ],
            options={
                'verbose_name': 'record access grant',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=400, upload_to=apps.tracking.models.attachment_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_uploads', to=settings.AUTH_USER_MODEL)),
                ('routing_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='tracking.routingstep')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tracking.trackingrecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='accounts.office')),
            ],
            options={
                'verbose_name': 'tracking number sequence',
                'unique_together': {('office', 'year', 'month')},
            },
        ),
        migrations.AddIndex(
            model_name='trackingrecord',
            index=models.Index(fields=['status', '-last_movement_at'], name='tracking_tr_status_5b89fa_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingrecord',
            index=models.Index(fields=['originating_office', '-created_at'], name='tracking_tr_origina_c2cc5d_idx'),
        ),
        migrations.AddIndex(
            model_name='routingstep',
            index=models.Index(fields=['to_office', 'received_at'], name='tracking_ro_to_offi_7c23c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routingstep',
            unique_together={('record', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='recordaccessgrant',
            unique_together={('record', 'office', 'user')},
        ),
    ]
