# Generated by Django 5.0.9 on 2026-08-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingrecord',
            name='requested_action',
            field=models.CharField(blank=True, choices=[('2', '2 · Appropriate Action'), ('3', '3 · Comment / Recommendation'), ('4', '4 · Study / Inquiry'), ('5', '5 · Reply Direct to Writer'), ('6', '6 · For Signature'), ('7', '7 · Rewrite / Redraft / Retype'), ('8', '8 · Notation to Return'), ('9', '9 · Notation to Forward'), ('10', '10 · Re-route'), ('11', '11 · File')], help_text='What the receiving office is being asked to do, as numbered on the routing slip.', max_length=2),
        ),
    ]
