# Generated by Django 5.0.9 on 2026-09-07 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_split_admin_from_system_admin'),
        ('core', '0007_notification_kinds'),
        ('tracking', '0005_record_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_days', models.PositiveSmallIntegerField(default=3, help_text='Calendar days the receiving office has to act. 0 means no deadline.')),
                ('is_active', models.BooleanField(default=True, help_text='Unticked rules are ignored, and the next tier down applies.')),
                ('document_type', models.ForeignKey(blank=True, help_text='Leave blank for a rule that applies to every document type.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_slas', to='core.documenttype')),
                ('office', models.ForeignKey(blank=True, help_text='Leave blank for a rule that applies to every office.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_slas', to='accounts.office')),
            ],
            options={
                'verbose_name': 'routing SLA',
                'verbose_name_plural': 'routing SLAs',
                'ordering': ['office__code', 'document_type__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='routingsla',
            constraint=models.UniqueConstraint(fields=('office', 'document_type'), name='unique_routing_sla_scope', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='routingsla',
            constraint=models.CheckConstraint(check=models.Q(('document_type__isnull', True), ('office__isnull', True), _negated=True), name='routing_sla_needs_a_scope'),
        ),
    ]
