# Generated by Django 5.0.9 on 2026-09-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_routingsla_routingsla_unique_routing_sla_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingrecord',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_RECEIPT', 'Pending Receipt'), ('RECEIVED', 'Received'), ('IN_PROCESS', 'In Process'), ('COMPLETED_PENDING_UPLOAD', 'Completed - Pending Upload'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=32),
        ),
    ]
