# Generated by Django 5.2.17 on 2026-10-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_status_labels_title_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingrecord',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_RECEIPT', 'Pending Receipt'), ('RECEIVED', 'Received'), ('IN_PROCESS', 'In Process'), ('COMPLETED_PENDING_UPLOAD', 'Pending filing'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=32),
        ),
    ]
