# Generated by Django 5.2.17 on 2026-10-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_pending_filing_display_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingrecord',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_RECEIPT', 'Pending Receipt'), ('RECEIVED', 'Received'), ('IN_PROCESS', 'In Process'), ('COMPLETED_PENDING_UPLOAD', 'Completed - Pending Filing'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=32),
        ),
    ]
